# Generated by Django 2.1.15 on 2022-06-26 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortenerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortenerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('short_url', models.TextField()),
                ('create_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
