# Generated by Django 2.1.15 on 2022-06-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortenerApp', '0002_urlshortenerresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshortenerresult',
            old_name='name',
            new_name='user',
        ),
    ]
