# Generated by Django 2.1.15 on 2022-06-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortenerApp', '0003_auto_20220626_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortenerresult',
            name='short_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
